spring:
  application:
    name: discovery-service
  main:
    banner-mode: off
logging:
  level:
    root: warn
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
